# Generated by Django 3.0.6 on 2020-08-19 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200819_1311'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='userEmail',
        ),
    ]
