# Generated by Django 3.0.6 on 2020-08-20 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200820_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='userEmail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
