# Generated by Django 3.0.6 on 2020-08-20 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_like_liked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='userEmail',
            field=models.EmailField(blank=True, default='Unknown User', max_length=254, null=True),
        ),
    ]
