# Generated by Django 3.0.6 on 2020-08-21 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200821_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('Politics', 'Politics'), ('Education', 'Education'), ('Foods', 'Foods'), ('Love and Relationship', 'LoveAndRelationship'), ('Gossip', 'Gossip'), ('Counselling', 'Counselling'), ('Technology', 'Technology'), ('Book', 'Book'), ('Religion', 'Religion'), ('Sports', 'Sports'), ('Technology', 'Technology'), ('Fashion', 'Fashion')], max_length=30),
        ),
    ]
